import type { Candidate, CalculateRoutePayload, Diagnostics, LiveTripPayload, PositionCache, PositionRow, PublicCandidate, SegmentInput, Serialized, Train } from "../types/domain";
import { cachedPositionRows, prefetchPositionCache, type FetchLike } from "./realtime-service";
import { activeTrainNoForVirtual, canonStation, chooseModes, firstCurrentIndex, formatKst, getTrain, indices, mergedContinuationTrain, nearestScheduleDt, nowKst, parseDt, routePair, routeTrains, resolveServiceMode, scheduleDtAfter, scheduleDtBefore, serviceOccurrenceMidnight, statusName, stopAlightSec, stopBoardSec, stopTimeSec, STATIONS_BY_LINE } from "./timetable-service";
import { autoCandidateRoutes, autoFindPath, autoPathToSegments, candidateInterchanges, enrichTransferSegments, routeConfidence } from "./routing-service";

const DAY_SECONDS = 86400;
const round = (n: number): number => Math.round(n);
const toDate = (value: unknown): Date | null => value instanceof Date ? value : null;
const serializeDate = (value: unknown): unknown => value instanceof Date ? formatKst(value) : value;

export function serializeSegment(value: Record<string, unknown>): Serialized { return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, serializeDate(v)])); }
export function stopReference(stops: Train["stops"], index: number, status: unknown): number | null { if (index < 0 || index >= stops.length) return null; const s = String(status ?? "").trim(); if (s === "3") { for (let j = index - 1; j >= 0; j -= 1) { const ref = stops[j].dep ?? stops[j].arr; if (ref !== null) return ref; } const arr = stops[index].arr; return arr === null ? null : arr - 60; } const stop = stops[index]; if (s === "2" && stop.dep !== null) return stop.dep; if (s === "1" && stop.arr !== null) return stop.arr; if (s === "0" && stop.arr !== null) return stop.arr - 30; return stop.dep ?? stop.arr; }

export function estimatedTrainLocation(train: Train, ref = nowKst(), delay = 0): { kind: "expected"; label: string; station: string; status: string } {
  const timed = train.stops.map((x, i) => [i, stopTimeSec(x)] as const).filter((x): x is readonly [number, number] => x[1] !== null); if (!timed.length) return { kind: "expected", label: "예상 소재 계산 불가", station: "", status: "" };
  const midnight = serviceOccurrenceMidnight(train, ref, delay); const timeline = timed.map(([i, sec]) => [i, new Date(midnight.getTime() + (sec + delay) * 1000)] as const); const [firstI, first] = timeline[0]; const [lastI, last] = timeline[timeline.length - 1];
  if (ref < first) { const station = canonStation(train.stops[firstI].station); return first.getTime() - ref.getTime() <= 3 * 3600000 ? { kind: "expected", label: `${station} 출발 전 예상`, station, status: "출발 전 예상" } : { kind: "expected", label: "운행 전", station: "", status: "운행 전" }; }
  if (ref > last) { const station = canonStation(train.stops[lastI].station); return ref.getTime() - last.getTime() <= 30 * 60000 ? { kind: "expected", label: `${station} 도착 추정`, station, status: "도착 추정" } : { kind: "expected", label: "운행 종료 추정", station, status: "운행 종료 추정" }; }
  const nearest = timeline.reduce((a, b) => Math.abs(a[1].getTime() - ref.getTime()) < Math.abs(b[1].getTime() - ref.getTime()) ? a : b); if (Math.abs(nearest[1].getTime() - ref.getTime()) <= 45000) { const stop = train.stops[nearest[0]]; const station = canonStation(stop.station); const passLike = nearest[0] !== 0 && nearest[0] !== train.stops.length - 1 && stop.arr === null; const status = passLike ? "통과 예상" : "부근 예상"; return { kind: "expected", label: `${station}역 ${status}`, station, status }; }
  for (let i = 0; i < timeline.length - 1; i += 1) if (timeline[i][1] <= ref && ref <= timeline[i + 1][1]) return { kind: "expected", label: `${canonStation(train.stops[timeline[i][0]].station)} → ${canonStation(train.stops[timeline[i + 1][0]].station)} 사이 예상`, station: "", status: "구간 운행 예상" };
  return { kind: "expected", label: "예상 소재 계산 중", station: "", status: "" };
}

export function observeDelays(line: string, mode: string, positions: PositionRow[]): [Array<ReturnType<typeof makeObservation>>, Diagnostics] {
  const observations: Array<ReturnType<typeof makeObservation>> = []; const unmatchedTrain: string[] = []; const unmatchedStation: string[] = [];
  for (const raw of positions) { const rawTrain = raw.trainNo ?? raw.btrainNo; const train = getTrain(line, mode, rawTrain); if (!train) { if (rawTrain && unmatchedTrain.length < 10) unmatchedTrain.push(String(rawTrain)); continue; } const current = canonStation(raw.statnNm); const index = firstCurrentIndex(train.stops, current); if (index === null) { if (current && unmatchedStation.length < 10) unmatchedStation.push(current); continue; } const ref = stopReference(train.stops, index, raw.trainSttus); if (ref === null) continue; const observed = parseDt(raw.recptnDt ?? raw.lastRecptnDt); observations.push(makeObservation({ train, raw, current, ref, observed, delay: (observed.getTime() / 1000 % DAY_SECONDS + DAY_SECONDS - ref) % DAY_SECONDS })); }
  // Align observed clock to the closest timetable occurrence, preserving negative delays.
  for (const item of observations) { const rawActual = item.observed.getUTCHours() * 3600 + item.observed.getUTCMinutes() * 60 + item.observed.getUTCSeconds(); const candidates = [rawActual - DAY_SECONDS, rawActual, rawActual + DAY_SECONDS, rawActual + 2 * DAY_SECONDS]; const aligned = candidates.reduce((a, b) => Math.abs(b - item.ref) < Math.abs(a - item.ref) ? b : a); item.delay = aligned - item.ref; }
  return [observations, { positions: positions.length, matched: observations.length, unmatched_train: unmatchedTrain, unmatched_station: unmatchedStation }];
}
function makeObservation(value: { train: Train; raw: PositionRow; current: string; ref: number; observed: Date; delay: number }) { return { train_no: value.train.train_no, direction: value.train.direction, service: value.train.service, delay: value.delay, current_station: value.current, status: statusName(value.raw.trainSttus), observed: value.observed, ref: value.ref, train: value.train, raw: value.raw }; }
export function medianDelay(observations: Array<{ direction: string; service: string; delay: number }>, direction?: string, service?: string): number { let values = observations.filter((x) => (!direction || x.direction === direction) && (!service || x.service === service)).map((x) => x.delay).filter((x) => Math.abs(x) <= 2700); if (!values.length && (direction || service)) return medianDelay(observations); if (!values.length) return 0; values.sort((a, b) => a - b); const i = Math.floor(values.length / 2); return values.length % 2 ? values[i] : (values[i - 1] + values[i]) / 2; }

function liveCandidates(line: string, mode: string, start: string, end: string, ready: Date, observations: ReturnType<typeof observeDelays>[0]): Candidate[] {
  const now = nowKst(); const out: Candidate[] = [];
  for (const o of observations) { let train = o.train; let stops = train.stops; let ci = firstCurrentIndex(stops, o.current_station); let pair = ci === null ? null : routePair(stops, start, end, ci); if (!pair && (line === "2호선" || line === "6호선")) { const virtual = mergedContinuationTrain(line, mode, train.train_no); if (virtual) { train = virtual; stops = train.stops; ci = firstCurrentIndex(stops, o.current_station); pair = ci === null ? null : routePair(stops, start, end, ci); } } if (ci === null || !pair || ci > pair[0]) continue; const ref = stopReference(stops, ci, o.raw.trainSttus); const boardSec = stopBoardSec(stops[pair[0]]); const alightSec = stopAlightSec(stops[pair[1]]); if (ref === null || boardSec === null || alightSec === null) continue; let bsec = boardSec; let asec = alightSec; while (bsec < ref) bsec += DAY_SECONDS; while (asec < bsec) asec += DAY_SECONDS; const age = Math.max(0, (now.getTime() - o.observed.getTime()) / 1000); const board = new Date(now.getTime() + (bsec - ref - age) * 1000); const alight = new Date(now.getTime() + (asec - ref - age) * 1000); if (board.getTime() < ready.getTime() - 5000) continue; out.push({ line, from: canonStation(start), to: canonStation(end), train_no: train.train_no, continuation_train_no: train.continuation_train_no ?? "", physical_continuation: Boolean(train.physical_continuation), service: train.service, direction: train.direction, origin: train.start, destination: train.dest, board_dt: board, alight_dt: alight, wait_seconds: round((board.getTime() - ready.getTime()) / 1000), ride_seconds: round((alight.getTime() - board.getTime()) / 1000), delay_seconds: round(o.delay), current_station: o.current_station, status: o.status, location_kind: "live", location_label: `${o.current_station} ${o.status}`, confidence: "높음", method: "실시간 열차 위치 + 열차별 공식 시간표", projected: false }); }
  return out.sort((a, b) => a.alight_dt.getTime() - b.alight_dt.getTime() || a.board_dt.getTime() - b.board_dt.getTime());
}
function projectedCandidates(line: string, mode: string, start: string, end: string, ready: Date, observations: ReturnType<typeof observeDelays>[0]): Candidate[] { const raw: Array<[Date, Date, Train, number]> = []; const now = nowKst(); for (const train of routeTrains(line, mode, start, end)) { const pair = routePair(train.stops, start, end); if (!pair) continue; const bsec = stopBoardSec(train.stops[pair[0]]); let asec = stopAlightSec(train.stops[pair[1]]); if (bsec === null || asec === null) continue; while (asec < bsec) asec += DAY_SECONDS; const delay = medianDelay(observations, train.direction, train.service); const board = scheduleDtAfter(bsec, ready, delay); if (!board || (board.getTime() - ready.getTime()) / 1000 > 14400) continue; raw.push([new Date(board.getTime() + (asec - bsec) * 1000), board, train, delay]); } raw.sort((a, b) => a[0].getTime() - b[0].getTime() || a[1].getTime() - b[1].getTime()); return raw.slice(0, 30).map(([alight, board, train, delay]) => { const location = estimatedTrainLocation(train, now, delay); return { line, from: canonStation(start), to: canonStation(end), train_no: train.train_no, continuation_train_no: train.continuation_train_no ?? "", physical_continuation: Boolean(train.physical_continuation), service: train.service, direction: train.direction, origin: train.start, destination: train.dest, board_dt: board, alight_dt: alight, wait_seconds: round((board.getTime() - ready.getTime()) / 1000), ride_seconds: round((alight.getTime() - board.getTime()) / 1000), delay_seconds: round(delay), current_station: location.station, status: location.status, location_kind: "expected", location_label: location.label, confidence: observations.length ? "중간" : "낮음", method: observations.length ? "공식 시간표 + 현재 동일방향 지연 중앙값" : "공식 시간표만 사용", projected: true }; }); }
function previousCandidate(line: string, mode: string, start: string, end: string, ready: Date, observations: ReturnType<typeof observeDelays>[0]): Candidate | null { let best: Candidate | null = null; for (const train of routeTrains(line, mode, start, end)) { const pair = routePair(train.stops, start, end); if (!pair) continue; const bsec = stopBoardSec(train.stops[pair[0]]); let asec = stopAlightSec(train.stops[pair[1]]); if (bsec === null || asec === null) continue; while (asec < bsec) asec += DAY_SECONDS; const delay = medianDelay(observations, train.direction, train.service); const board = scheduleDtBefore(bsec, ready, delay); if (!board) continue; const alight = new Date(board.getTime() + (asec - bsec) * 1000); if (alight.getTime() < nowKst().getTime() - 120000) continue; const location = estimatedTrainLocation(train, nowKst(), delay); const candidate: Candidate = { line, from: canonStation(start), to: canonStation(end), train_no: train.train_no, continuation_train_no: train.continuation_train_no ?? "", physical_continuation: Boolean(train.physical_continuation), service: train.service, direction: train.direction, origin: train.start, destination: train.dest, board_dt: board, alight_dt: alight, wait_seconds: round((board.getTime() - ready.getTime()) / 1000), ride_seconds: round((alight.getTime() - board.getTime()) / 1000), delay_seconds: round(delay), current_station: location.station, status: location.status, location_kind: "expected", location_label: location.label, confidence: observations.length ? "중간" : "낮음", method: observations.length ? "직전 열차 추정 · 공식 시간표 + 현재 지연" : "직전 열차 추정 · 공식 시간표", projected: true }; if (!best || candidate.board_dt.getTime() > best.board_dt.getTime()) best = candidate; } return best; }
export function publicCandidate(c: Candidate | null, selected = false): PublicCandidate | null { if (!c) return null; return { train_no: c.train_no, continuation_train_no: c.continuation_train_no, physical_continuation: c.physical_continuation, service: c.service, direction: c.direction, origin: c.origin, destination: c.destination, board_dt: formatKst(c.board_dt), alight_dt: formatKst(c.alight_dt), wait_seconds: c.wait_seconds, ride_seconds: c.ride_seconds, delay_seconds: c.delay_seconds, current_station: c.current_station, status: c.status, location_kind: c.location_kind, location_label: c.location_label, confidence: c.confidence, method: c.method, projected: c.projected, live_detected: !c.projected, selected }; }

export async function calculateSegment(line: string, mode: string, start: string, end: string, ready: Date, cache: PositionCache, fetchImpl: FetchLike = fetch): Promise<{ ok: boolean; chosen?: Candidate; candidates?: Candidate[]; public_candidates?: PublicCandidate[]; previous_candidate?: PublicCandidate | null; diagnostics?: Diagnostics; error?: string }> {
  if (!STATIONS_BY_LINE[line]) return { ok: false, error: `지원하지 않는 노선: ${line}` }; const lineStations = new Set(STATIONS_BY_LINE[line].map(canonStation)); if (!lineStations.has(canonStation(start))) return { ok: false, error: `${line} 시간표에서 승차역 '${start}'을 찾지 못했습니다.` }; if (!lineStations.has(canonStation(end))) return { ok: false, error: `${line} 시간표에서 하차역 '${end}'을 찾지 못했습니다.` };
  const realtime = await cachedPositionRows(line, cache, 5, fetchImpl); const [observations, diagnostics] = observeDelays(line, mode, realtime.rows); diagnostics.realtime_available = realtime.available; if (realtime.error) diagnostics.realtime_error = realtime.error; const direct = liveCandidates(line, mode, start, end, ready, observations); const projected = projectedCandidates(line, mode, start, end, ready, observations); const merged = new Map<string, Candidate>(); for (const c of projected) merged.set(c.train_no, c); for (const c of direct) merged.set(c.train_no, c); let candidates = [...merged.values()]; let near = candidates.filter((c) => { const s = (c.board_dt.getTime() - ready.getTime()) / 1000; return s >= -5 && s <= 3600; }); if (!near.length) near = candidates; near.sort((a, b) => a.alight_dt.getTime() - b.alight_dt.getTime() || a.board_dt.getTime() - b.board_dt.getTime()); if (!near.length) return { ok: false, error: `${line} ${start}→${end} 운행 열차를 현재 시간표에서 찾지 못했습니다.`, diagnostics }; const chosen = near[0]; return { ok: true, chosen, candidates: near.slice(0, 10), public_candidates: near.slice(0, 6).map((c) => publicCandidate(c, c.train_no === chosen.train_no) as PublicCandidate), previous_candidate: publicCandidate(previousCandidate(line, mode, start, end, ready, observations)), diagnostics }; }

export async function trackedTrainSegment(line: string, mode: string, start: string, end: string, trainNo: string, cache: PositionCache, boardedAt?: string, fetchImpl: FetchLike = fetch): Promise<{ ok: boolean; arrived?: boolean; chosen?: Candidate & Record<string, unknown>; diagnostics?: Diagnostics; error?: string }> {
  const now = nowKst(); const base = getTrain(line, mode, trainNo); if (!base) return { ok: false, error: `${line} 공식 시간표에서 탑승 열차 ${trainNo}을 찾지 못했습니다.` }; let train = base; let pair = routePair(train.stops, start, end); if (!pair && (line === "2호선" || line === "6호선")) { const virtual = mergedContinuationTrain(line, mode, base.train_no); if (virtual && routePair(virtual.stops, start, end)) { train = virtual; pair = routePair(train.stops, start, end); } } if (!pair) return { ok: false, error: `${trainNo}열차 시간표에서 ${start}→${end} 운행 구간을 찾지 못했습니다.` }; const targetSec = stopAlightSec(train.stops[pair[1]]); if (targetSec === null) return { ok: false, error: `${end} 도착시각이 시간표에 없습니다.` }; const realtime = await cachedPositionRows(line, cache, 5, fetchImpl); const [observations, diagnostics] = observeDelays(line, mode, realtime.rows); diagnostics.realtime_available = realtime.available; if (realtime.error) diagnostics.realtime_error = realtime.error; const wanted = new Set([train.train_no, train.continuation_train_no ?? ""].map((x) => x.toUpperCase())); const live = observations.filter((x) => wanted.has(x.train_no.toUpperCase())).sort((a, b) => b.observed.getTime() - a.observed.getTime())[0]; let boarded = boardedAt ? parseDt(boardedAt) : null;
  if (live) { let ci = firstCurrentIndex(train.stops, live.current_station, pair[1]); ci ??= firstCurrentIndex(train.stops, live.current_station); const arrived = ci !== null && (ci > pair[1] || (ci === pair[1] && ["도착", "출발"].includes(live.status))); if (arrived) return { ok: true, arrived: true, chosen: trackedCandidate(line, start, end, train, live, boarded ?? now, now, now, 0, true), diagnostics }; if (ci !== null) { const ref = stopReference(train.stops, ci, live.raw.trainSttus); if (ref !== null) { let target = targetSec; while (target < ref) target += DAY_SECONDS; const age = Math.max(0, (now.getTime() - live.observed.getTime()) / 1000); let remaining = target - ref - age; const alight = remaining > 21600 ? nearestScheduleDt(targetSec, now, live.delay) : new Date(now.getTime() + Math.max(0, remaining) * 1000); if (boarded && boarded > alight) boarded = alight; return { ok: true, arrived: false, chosen: trackedCandidate(line, start, end, train, live, boarded ?? now, alight, now, Math.max(0, round((alight.getTime() - now.getTime()) / 1000)), false), diagnostics }; } } }
  const direction = train.physical_continuation && activeTrainNoForVirtual(train, now) === train.continuation_train_no ? (train.continuation_direction ?? train.direction) : train.direction; const delay = medianDelay(observations, direction, train.service); const location = estimatedTrainLocation(train, now, delay); let target = nearestScheduleDt(targetSec, now, delay); if (target.getTime() < now.getTime() - 300000 || target.getTime() > now.getTime() + 21600000) target = now; return { ok: true, arrived: false, chosen: { line, from: canonStation(start), to: canonStation(end), train_no: activeTrainNoForVirtual(train, now, delay), continuation_train_no: train.continuation_train_no ?? "", physical_continuation: Boolean(train.physical_continuation), service: train.service, direction, origin: train.start, destination: train.dest, board_dt: boarded ?? now, alight_dt: target, wait_seconds: 0, ride_seconds: Math.max(0, round((target.getTime() - (boarded ?? now).getTime()) / 1000)), remaining_seconds: Math.max(0, round((target.getTime() - now.getTime()) / 1000)), delay_seconds: round(delay), current_station: location.station, status: location.status || "위치 재포착 대기", location_kind: "expected", location_label: location.label, confidence: observations.length ? "중간" : "낮음", method: realtime.available ? (train.physical_continuation ? "연속운행 열차 잠금 · 실시간 위치 재포착 대기" : "탑승 열차 잠금 · 실시간 위치 재포착 대기") : "공식 시간표 기반 임시 추적 · 실시간 위치 조회 실패", projected: true, tracking: true, arrived: false }, diagnostics }; }
function trackedCandidate(line: string, start: string, end: string, train: Train, live: ReturnType<typeof makeObservation>, board: Date, alight: Date, now: Date, remaining: number, arrived: boolean): Candidate & Record<string, unknown> { return { line, from: canonStation(start), to: canonStation(end), train_no: live.train_no, continuation_train_no: train.continuation_train_no ?? "", physical_continuation: Boolean(train.physical_continuation), service: train.service, direction: live.direction || train.direction, origin: train.start, destination: train.dest, board_dt: board, alight_dt: alight, wait_seconds: 0, ride_seconds: arrived ? 0 : Math.max(0, round((alight.getTime() - board.getTime()) / 1000)), remaining_seconds: arrived ? 0 : remaining, delay_seconds: round(live.delay), current_station: live.current_station, status: live.status, location_kind: "live", location_label: `${live.current_station} ${live.status}`, confidence: "높음", method: train.physical_continuation ? "탑승 열차 연속운행 추적" : "탑승 열차 실시간 고정 추적", projected: false, tracking: true, arrived }; }

export async function calculateRoute(payload: CalculateRoutePayload, positionCache?: PositionCache, fetchImpl: FetchLike = fetch): Promise<Serialized> {
  const segments = payload.segments ?? []; if (segments.length < 1 || segments.length > 8) throw new Error("구간은 1~8개로 입력하세요."); const now = nowKst(); let start = payload.start_time ? (clockDtNearForPayload(payload.start_time, now)) : now; if (start.getTime() < now.getTime() - 8 * 3600000) start = new Date(start.getTime() + 86400000); const [mode, reason] = resolveServiceMode(String(payload.day ?? "AUTO"), start); const refresh = Boolean(payload.refresh_only); const readyBase = refresh ? new Date(Math.max(start.getTime(), now.getTime())) : start; const cache = positionCache ?? await prefetchPositionCache(segments.map((x) => String(x.line)), 5, fetchImpl); const results: Array<Record<string, unknown>> = []; const warnings: string[] = []; let ready = readyBase;
  for (let i = 0; i < segments.length; i += 1) { const s = segments[i]; const line = String(s.line ?? "").trim(); const from = canonStation(s.from); const to = canonStation(s.to); if (!from || !to) throw new Error(`${i + 1}번 구간의 승차역/하차역을 입력하세요.`); if (from === to) throw new Error(`${i + 1}번 구간의 승차역과 하차역이 같습니다.`); const r = await calculateSegment(line, mode, from, to, ready, cache, fetchImpl); if (!r.ok || !r.chosen) return { ok: false, failed_segment: i + 1, error: r.error ?? "구간 계산 실패", diagnostics: r.diagnostics ?? {}, partial_segments: results.map(serializeSegment) }; const chosen: Record<string, unknown> = { ...r.chosen, segment_index: i + 1, ready_dt: ready, diagnostics: r.diagnostics ?? {}, nearby_candidates: r.public_candidates ?? [], previous_candidate: r.previous_candidate ?? null, transfer_info: s.transfer_info ?? null, transfer_seconds: Number(s.transfer_seconds ?? Math.round(Number(s.transfer_walk ?? 0) * 60) ) }; results.push(chosen); if (r.chosen.confidence !== "높음") warnings.push(`${i + 1}구간 ${line} ${from}→${to}: ${r.chosen.method} (${r.chosen.confidence} 신뢰도)`); const transfer = Math.max(0, Number(s.transfer_seconds ?? Math.round(Number(s.transfer_walk ?? 0) * 60))); ready = new Date(r.chosen.alight_dt.getTime() + (i < segments.length - 1 ? transfer * 1000 : 0)); }
  const end = results[results.length - 1].alight_dt as Date; let baseline: number | null = null; if (payload.baseline_minutes !== "" && payload.baseline_minutes !== null && payload.baseline_minutes !== undefined) { const parsed = Number(payload.baseline_minutes); if (Number.isFinite(parsed)) baseline = parsed; }
  return { ok: true, service_mode: mode, service_mode_reason: reason, start_time: formatKst(start), calculated_at: formatKst(now), refresh_only: refresh, arrival_time: formatKst(end), total_seconds: round((end.getTime() - start.getTime()) / 1000), baseline_minutes: baseline, difference_seconds: baseline === null ? null : round((end.getTime() - start.getTime()) / 1000 - baseline * 60), segments: results.map(serializeSegment), warnings };
}

function clockDtNearForPayload(text: string, ref: Date): Date { return /^\d{4}-\d{2}-\d{2}[ T]/.test(text) ? parseDt(text) : (awaitlessClock(text, ref)); }
function awaitlessClock(text: string, ref: Date): Date { const m = text.match(/^(\d{1,2}):(\d{2})(?::(\d{2}))?$/); if (!m) return parseDt(text); const sec = Number(m[1]) * 3600 + Number(m[2]) * 60 + Number(m[3] ?? 0); const base = new Date(Date.UTC(ref.getUTCFullYear(), ref.getUTCMonth(), ref.getUTCDate())); return [-1, 0, 1].map((d) => new Date(base.getTime() + d * 86400000 + sec * 1000)).reduce((a, b) => Math.abs(a.getTime() - ref.getTime()) < Math.abs(b.getTime() - ref.getTime()) ? a : b); }

export async function calculateLiveTrip(payload: LiveTripPayload, fetchImpl: FetchLike = fetch): Promise<Serialized> {
  const segments = payload.segments ?? []; if (segments.length < 1 || segments.length > 8) throw new Error("구간은 1~8개로 입력하세요."); const activeIndex = Number(payload.active_index ?? 0); if (activeIndex < 0 || activeIndex >= segments.length) throw new Error("추적 중인 구간 번호가 올바르지 않습니다."); const boardedNo = String(payload.boarded_train_no ?? "").trim(); if (!boardedNo) throw new Error("탑승한 열차번호가 없습니다."); const ref = payload.boarded_at ? parseDt(payload.boarded_at) : nowKst(); const [mode, reason] = resolveServiceMode(String(payload.day ?? "AUTO"), ref); const cache = await prefetchPositionCache(segments.map((x) => String(x.line)), 5, fetchImpl); const results: Array<Record<string, unknown>> = []; const warnings: string[] = []; const active = segments[activeIndex]; const tracked = await trackedTrainSegment(String(active.line ?? ""), mode, canonStation(active.from), canonStation(active.to), boardedNo, cache, typeof payload.boarded_at === "string" ? payload.boarded_at : undefined, fetchImpl); if (!tracked.ok || !tracked.chosen) return { ok: false, failed_segment: activeIndex + 1, error: tracked.error ?? "탑승 열차 추적 실패", diagnostics: tracked.diagnostics ?? {} }; const activeCurrent: Record<string, unknown> = { ...tracked.chosen, segment_index: activeIndex + 1, diagnostics: tracked.diagnostics ?? {}, nearby_candidates: [publicCandidate(tracked.chosen as Candidate, true)], transfer_info: active.transfer_info ?? null, transfer_seconds: Number(active.transfer_seconds ?? Math.round(Number(active.transfer_walk ?? 0) * 60)) }; results.push(activeCurrent); let ready = new Date((activeCurrent.alight_dt as Date).getTime() + (activeIndex < segments.length - 1 ? Number(activeCurrent.transfer_seconds ?? 0) * 1000 : 0)); for (let i = activeIndex + 1; i < segments.length; i += 1) { const s = segments[i]; const r = await calculateSegment(String(s.line ?? ""), mode, canonStation(s.from), canonStation(s.to), ready, cache, fetchImpl); if (!r.ok || !r.chosen) return { ok: false, failed_segment: i + 1, error: r.error ?? "후속 구간 계산 실패", diagnostics: r.diagnostics ?? {}, segments: results.map(serializeSegment) }; const nextChosen: Record<string, unknown> = { ...r.chosen, segment_index: i + 1, ready_dt: ready, diagnostics: r.diagnostics ?? {}, nearby_candidates: r.public_candidates ?? [], previous_candidate: r.previous_candidate ?? null, transfer_info: s.transfer_info ?? null, transfer_seconds: Number(s.transfer_seconds ?? Math.round(Number(s.transfer_walk ?? 0) * 60)) }; results.push(nextChosen); if (r.chosen.confidence !== "높음") warnings.push(`${i + 1}구간 ${s.line} ${s.from}→${s.to}: ${r.chosen.method} (${r.chosen.confidence} 신뢰도)`); ready = new Date(r.chosen.alight_dt.getTime() + (i < segments.length - 1 ? Number(nextChosen.transfer_seconds ?? 0) * 1000 : 0)); }
  const now = nowKst(); const final = results[results.length - 1].alight_dt as Date; return { ok: true, live_tracking: true, service_mode: mode, service_mode_reason: reason, active_index: activeIndex, boarded_train_no: activeCurrent.train_no ?? boardedNo, updated_at: formatKst(now), arrival_time: formatKst(final), remaining_seconds: Math.max(0, round((final.getTime() - now.getTime()) / 1000)), current_segment_remaining_seconds: Number(activeCurrent.remaining_seconds ?? 0), current_station: String(activeCurrent.current_station ?? ""), current_status: String(activeCurrent.status ?? ""), segments: results.map(serializeSegment), warnings };
}

export interface AutoRouteLiveScore {
  path: { seconds: number };
  segments: SegmentInput[];
  result: Serialized;
  scheduleResult: Serialized;
}

export function compareAutoRouteLiveScores(a: AutoRouteLiveScore, b: AutoRouteLiveScore): number {
  return String(a.result.arrival_time).localeCompare(String(b.result.arrival_time))
    || a.segments.length - b.segments.length
    || String(a.scheduleResult.arrival_time).localeCompare(String(b.scheduleResult.arrival_time))
    || a.path.seconds - b.path.seconds;
}

export async function calculateAutoRoute(payload: { from: string; to: string; start_time?: string; day?: string; [key: string]: unknown }, fetchImpl: FetchLike = fetch): Promise<Serialized> {
  const now = nowKst(); let start = payload.start_time ? clockDtNearForPayload(payload.start_time, now) : now; if (start.getTime() < now.getTime() - 8 * 3600000) start = new Date(start.getTime() + 86400000); const [mode, reason] = resolveServiceMode(String(payload.day ?? "AUTO"), start); const startStation = canonStation(payload.from); const endStation = canonStation(payload.to); const candidates = autoCandidateRoutes(startStation, endStation, mode); const scheduleCache: PositionCache = new Map(); for (const line of Object.keys(STATIONS_BY_LINE)) { if (scheduleCache instanceof Map) scheduleCache.set(line, { rows: [], error: "자동경로 시간표 사전채점", available: false }); }
  const scoredSchedule: Array<{ path: (typeof candidates)[number]["path"]; segments: SegmentInput[]; result: Serialized }> = [];
  for (const candidate of candidates) { const result = await calculateRoute({ start_time: formatKst(start), day: mode, segments: candidate.segments, refresh_only: false }, scheduleCache, fetchImpl); if (result.ok) scoredSchedule.push({ path: candidate.path, segments: candidate.segments, result }); }
  if (!scoredSchedule.length) { const path = autoFindPath(startStation, endStation, mode); const segments = enrichTransferSegments(autoPathToSegments(path, mode), mode); return { ok: true, service_mode: mode, service_mode_reason: reason, from: startStation, to: endStation, route_seconds: path.seconds, transfer_count: Math.max(0, segments.length - 1), interchanges: candidateInterchanges(segments), segments, selection_method: "정적 그래프 fallback", candidate_count: 1, live_scored_count: 0, alternatives: [] };
  }
  scoredSchedule.sort((a, b) => String(a.result.arrival_time).localeCompare(String(b.result.arrival_time)) || (a.segments.length - b.segments.length) || a.path.seconds - b.path.seconds); const lines = [...new Set(scoredSchedule.flatMap((x) => x.segments.map((s) => String(s.line))) )]; const liveCache = await prefetchPositionCache(lines, 5, fetchImpl); const liveScored: AutoRouteLiveScore[] = [];
  for (const candidate of scoredSchedule) { const result = await calculateRoute({ start_time: formatKst(start), day: mode, segments: candidate.segments, refresh_only: false }, liveCache, fetchImpl); liveScored.push({ path: candidate.path, segments: candidate.segments, result: result.ok ? result : candidate.result, scheduleResult: candidate.result }); }
  liveScored.sort(compareAutoRouteLiveScores); const selected = liveScored[0]; const selectedResult = selected.result; const alternatives = liveScored.slice(1, 4).map((item) => ({ segments: item.segments, interchanges: candidateInterchanges(item.segments), transfer_count: Math.max(0, item.segments.length - 1), route_seconds: item.path.seconds, total_seconds: Number(item.result.total_seconds ?? 0), arrival_time: item.result.arrival_time, confidence: routeConfidence(item.result as { segments?: Array<{ confidence?: string }> }) })); return { ok: true, service_mode: mode, service_mode_reason: reason, from: startStation, to: endStation, route_seconds: selected.path.seconds, estimated_total_seconds: Number(selectedResult.total_seconds ?? 0), estimated_arrival_time: selectedResult.arrival_time, estimated_confidence: routeConfidence(selectedResult as { segments?: Array<{ confidence?: string }> }), transfer_count: Math.max(0, selected.segments.length - 1), interchanges: candidateInterchanges(selected.segments), segments: selectedResult.segments ?? selected.segments, selection_method: "다중 후보 시간표 + 실시간 ETA 비교", candidate_count: candidates.length, live_scored_count: liveScored.length, alternatives };
}

export { formatKst, nowKst };
