import { describe, expect, test } from "bun:test";
import { calculateAutoRoute, calculateLiveTrip, calculateRoute, healthSnapshot, stationsByLine } from "../../src/engine/index";
import { fetchPosition } from "../../src/engine/realtime-service";
import { canonStation, clockDtNear, nowKst, resolveServiceMode } from "../../src/engine/timetable-service";
import { compareAutoRouteLiveScores, type AutoRouteLiveScore } from "../../src/engine/eta-service";
import { JsonDataRepository } from "../../src/engine/data-repository";
import { autoFindPath, bestTransferDetail } from "../../src/engine/routing-service";

describe("지금타 Bun engine", () => {
  test("KST naive clock and aliases stay stable", () => { const value = clockDtNear("10:30:00", nowKst()); expect(value.getUTCHours()).toBe(10); expect(canonStation("총신대입구 역")).toBe("총신대입구(이수)"); });
  test("service mode resolves manual mode without host timezone", () => { const [mode, reason] = resolveServiceMode("DAY", nowKst()); expect(mode).toBe("DAY"); expect(reason).toBe("평일 수동 선택"); });
  test("all supported lines expose station options including Shinbundang and both GTX-A sections", () => {
    expect(Object.keys(stationsByLine)).toHaveLength(18);
    expect(stationsByLine["2호선"]).toContain("강남"); expect(stationsByLine["공항철도"]).toContain("서울역");
    expect(stationsByLine["신분당선"]).toContain("강남"); expect(stationsByLine["GTX-A(북부)"]).toEqual(["운정중앙", "킨텍스", "대곡", "연신내", "서울역"]); expect(stationsByLine["GTX-A(남부)"]).toEqual(["수서", "성남", "구성", "동탄"]);
  });
  test("route graph finds a direct timetable path", () => { const path = autoFindPath("강남", "잠실", "DAY"); expect(path.edges.length).toBeGreaterThan(0); expect(path.seconds).toBeGreaterThan(0); });
  test("교대 transfer chooses the exact incoming/outgoing direction record", () => { expect(bestTransferDetail("교대", { line: "2호선", from: "강남", to: "교대" }, { line: "3호선", from: "교대", to: "고속터미널" }, "DAY")).toMatchObject({ station: "교대", distance_m: 75, alight_position: "1-2", board_position: "7-4", matched: "direction" }); });
  test("live ETA tie uses schedule arrival before static path seconds", () => { const common = { result: { arrival_time: "2026-08-18 10:30:00" }, segments: [{ line: "2호선", from: "강남", to: "잠실" }] }; const laterScheduleShortPath: AutoRouteLiveScore = { ...common, path: { seconds: 100 }, scheduleResult: { arrival_time: "2026-08-18 10:20:00" } }; const earlierScheduleLongPath: AutoRouteLiveScore = { ...common, path: { seconds: 900 }, scheduleResult: { arrival_time: "2026-08-18 10:10:00" } }; expect([laterScheduleShortPath, earlierScheduleLongPath].sort(compareAutoRouteLiveScores)[0]).toBe(earlierScheduleLongPath); });
  test("data repository parses schedule payloads only when requested", () => { const lazy = new JsonDataRepository(); expect(lazy.loadedDatasets()).toEqual([]); expect(lazy.validate()).toMatchObject({ stationLines: 16, graphModes: ["DAY", "SAT", "END"] }); expect(lazy.loadedDatasets()).toEqual(["graph"]); expect(Object.keys(lazy.data.s1.weekday)).toHaveLength(843); expect(lazy.loadedDatasets()).toEqual(["graph", "s1-weekday"]); });
  test("route falls back to timetable when realtime is unavailable", async () => { const cache = new Map([["2호선", { rows: [], error: "fixture timeout", available: false }]]); const result = await calculateRoute({ day: "DAY", start_time: "10:00", segments: [{ line: "2호선", from: "강남", to: "잠실" }] }, cache); expect(result.ok).toBe(true); expect(result.segments).toBeArray(); const first = (result.segments as Array<Record<string, unknown>>)[0]; expect(first.diagnostics).toMatchObject({ realtime_available: false }); });
  test("health snapshot contains cache/realtime diagnostics and never exposes the key", () => { const health = healthSnapshot(); expect(health.ok).toBe(true); expect(health).toMatchObject({ line1_weekday_trains: 843, line1_holiday_trains: 729, metro_source: "250930", upstream_parity: "V13.4.8" }); expect(health.api_key_configured).toBeBoolean(); expect(health.cache).toBeObject(); expect(JSON.stringify(health)).not.toContain("SEOUL_API_KEY="); });
  test("Shinbundang ignores random API train numbers and context-matches timetable trains", async () => { const old = Bun.env.SEOUL_API_KEY; Bun.env.SEOUL_API_KEY = "test"; try { const result = await fetchPosition("신분당선", 5, async () => new Response(JSON.stringify({ realtimePositionList: [{ subwayId: "1077", trainNo: "7", statnNm: "강남", statnTnm: "광교", updnLine: "하행", trainSttus: "2", recptnDt: "2026-08-18 10:00:00" }] }))); const row = result.data?.realtimePositionList?.[0]; expect(result.ok).toBe(true); expect(row?._jigeumta_raw_train_no).toBe("7"); expect(row?.trainNo).not.toBe("7"); expect(String(row?.trainNo || "")).toStartWith("DX"); } finally { if (old == null) delete Bun.env.SEOUL_API_KEY; else Bun.env.SEOUL_API_KEY = old; } });
  test("GTX-A direct routing consumes realtimePosition rows", async () => { const old = Bun.env.SEOUL_API_KEY; Bun.env.SEOUL_API_KEY = "test"; try { const result = await calculateAutoRoute({ from: "수서", to: "동탄", day: "DAY", start_time: "2026-08-18 10:00:00" }, async () => new Response(JSON.stringify({ realtimePositionList: [{ subwayId: "1032", trainNo: "A101", statnNm: "수서", statnTnm: "동탄", trainSttus: "2", recptnDt: "2026-08-18 10:00:00" }] }))); expect(result.ok).toBe(true); expect((result.segments as Array<Record<string, unknown>>)[0]).toMatchObject({ line: "GTX-A(남부)", train_no: "A101", confidence: "높음" }); } finally { if (old == null) delete Bun.env.SEOUL_API_KEY; else Bun.env.SEOUL_API_KEY = old; } });
  test("ordinary live trip keeps the active tracked train identity", async () => { const result = await calculateLiveTrip({ day: "DAY", active_index: 0, boarded_train_no: "2143", boarded_at: "2026-08-18 10:00:00", segments: [{ line: "2호선", from: "강남", to: "잠실" }] }, async () => new Response(JSON.stringify({ realtimePositionList: [] }))); expect(result.ok).toBe(true); expect(result.boarded_train_no).toBe("2143"); expect(result.active_index).toBe(0); });
});
